```yaml
name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build || echo "No build script"

      - name: Docker Build
        run: docker build -t chat-app .

      - name: Deploy to Render (example)
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
```
